/**
 *	@author Ariana Fairbanks
 */

package model;

public enum Movement 
{
	ROAD, HILL, ENTER, UPSTREAM, DOWNSTREAM, FOREST, FORWARD, BACK, 
	VALLEY, STAIRS, OUT, BUILDING, GULLY, STREAM, ROCK, BED, CRAWL, 
	COBBLE, IN, SURFACE, NOWHERE, DARK, PASSAGE, LOW, CANYON, 
	AWKWARD, GIANT, VIEW, UP, DOWN, PIT, OUTDOORS, CRACK, STEPS, DOME,
	LEFT, RIGHT, HALL, JUMP, BARREN, OVER, ACROSS, EAST, WEST, NORTH, 
	SOUTH, NORTHEAST, SOUTHEAST, SOUTHWEST,NORTHWEST, 
	DEBRIS, HOLE, WALL, BROKEN, Y2, CLIMB, FLOOR, ROOM, 
	SLIT, SLAB, XYZZY, DEPRESSION, ENTRANCE, PLUGH, SECRET, CAVE,
	CROSS, BEDQUILT, PLOVER, ORIENTAL, CAVERN, SHELL, RESERVOIR,
	OFFICE, FORK
}